collections:
  - name: community.vmware
  
  - name: vyos.vyos

  - name: cisco.ios

  - name: arista.eos

  - name: ansible.netcommon
  
  - name: google.cloud
   
  - name: amazon.aws
    
  - name: community.aws
    
  - name: servicenow.itsm
    
  - name: community.general
    
  - name: community.crypto
  
  - name: azure.azcollection
