---
- name: Adding VLANs
  hosts: switches
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Show run
      ios_vlans:
        config:
          - name: Vlan_330
            vlan_id: 330
            state: active
            shutdown: enabled
        state: merged
