---
- name: Add IP Address
  hosts: routers
  connection: network_cli
  gather_facts: no

tasks:
  - name: add ip address
    ios_config:
      lines:
        - interface Serial 0/3/0
        - ip address 10.1.80.1 255.255.255.0
        - shutdown
        - no shutdown
