---
- name: Adding VLAN
  hosts: switch_a
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Add VLAN
      ios_vlans:
        config:
          - name: Vlan_330
            vlan_id: 330
            state: active
        state: merged
