---
- name: Add IP Address
  hosts: routers
  connection: network_cli
  gather_facts: no

- name: Merge provided ip address
  ios_l3_interfaces:
    config:
      - name: Serial 0/3/0
        ipv4:
        - address: 10.1.10.1/24
    state: merged
