---
- name: add ip Address
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: add ip Address
      ios_config:
        line:
          - ip address 10.1.80.1 255.255.255.0
        parents: interface serial 0/3/0
        become: yes

    - name: shutdown interface
      ios_config:
        lines:
          - shutdown
        parents: interface serial 0/3/0
        become: yes

    - name: turn on interface
      ios_config:
        line:
          - no shutdown
        parents: interface serial 0/3/0
        become: yes
