---
- name: Adding VLAN
  hosts: switch_a
  connection: network_cli
  gather_facts: no

  tasks:
  - name: add vlan
    ios_command:
     commands:
       - c1sc0
       - vlan 330
       - name vlanTest
       - end
