---
- name: Adding VLAN
  hosts: switch_a
  connection: network_cli
  gather_facts: no
  become_method: enable

  tasks:
  - name: add vlan
    ios_command:
     lines:
       - vlan 330
       - name vlanTest
       - end
