---
- name: Adding VLAN
  hosts: switch_a
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Merge provided configuration with device configuration
  ios_vlans:
    config:
      - name: Vlan_400
        vlan_id: 400
        state: active
        shutdown: enabled
    state: merged
