---
- hosts: localhost
  gather_facts: no
  connection: local
  collections: 
    - community.general
    - community.vmware

  tasks: 
    - name: Deploy Virtual Machine from template in content library
      community.vmware.vmware_content_deploy_template:
        hostname: 192.168.1.52
        host: 192.168.1.8
        username: administrator@vcenter.mdblab
        password: Vmware1!
        validate_certs: no 
        name: Sample_RHEL_VM
        template: RHEL_Template
        content_library: test_content_library
        datastore: datastore1
        datacenter: mdblabdatacenter
        state: present
      delegate_to: localhost
