---
- name: Show Version and interfaces
  hosts: switches
  connection: network_cli
  gather_facts: no

  tasks:
  - name: run multiple commands and evaluate output
    ios_command:
      commands:
        - show version
        - show interfaces
      register: showversion

    - name: Print out version
      debug:
        var: showversion.stdout
