---
- name: Show Running Config
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
  - name: show running config
     cisco.ios.ios_config:
       lines: 
       - show run
     register: showrun

  - name: Print out running config
    debug:
      var: showrun.stdout   







# - name: Show run
  # ios_command:
    # commands:
      # - show running-config
  # register: showrun


