---
- name: Show Running Config
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Show run
      ios_command:
        commands:
          - show running-config
      register: showrun

    - name: Print out running config
      debug:
        var: showrun.stdout
