---
- name: Show VLANs
  hosts: switches
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Show vlans
      ios_command:
        commands:
          - show vlan
      register: showrun

    - name: Print out vlans
      debug:
        var: showrun.stdout
