---
- name: Show Running Config
  hosts: routers
 #vars: 
   #ansible_connection: network_cli
  gather_facts: no

  tasks:
  - name: show running config and back up
    ios_config:
      backup: true
    register: config_output
     #commands: 
     #- show running-config
   #register: showrun

  - name: Print out running config
    debug:
      var: config_output.stdout 
     #var: showrun.stdout   







# - name: Show run
  # ios_command:
    # commands:
      # - show running-config
  # register: showrun


