---
- name: Show Running Config
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
  - name: configure interface settings
     cisco.ios.ios_config:
     commands: show r

  - name: Print out running config
    debug:
      var: showrun.stdout   







# - name: Show run
  # ios_command:
    # commands:
      # - show running-config
  # register: showrun


