---
- name: Delete VLAN Access Ports
  hosts: switch_a
  connection: network_cli
  gather_facts: no

  tasks:
    # - name: Adding vlan
    #   ios_vlans:
    #     config:
    #       - name: Vlan_220
    #         vlan_id: 220
    #         state: active
    #     state: merged
      # become: yes
    - name: Delete vlan access port
      ios_config:
        commands:
          - switchport mode access
          - no switchport access vlan 30
          - shutdown
          - no shutdown
        parents: interface range fastEthernet 2/0/1 - 16
      become: yes
