---
- name: Trunk VLAN Access Ports
  hosts: switch_b
  connection: network_cli
  gather_facts: no

  tasks:
    # - name: Adding vlan
    #   ios_vlans:
    #     config:
    #       - name: Vlan_220
    #         vlan_id: 220
    #         state: active
    #     state: merged
      # become: yes
    - name: trunk vlan access port
      ios_config:
        commands:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - shutdown
          - no shutdown
        parents: interface fastEthernet 1/0/48
      become: yes
