---
- name: Test IOS Facts
  hosts: cisco
  tasks:
    - debug:
        var: ansible_facts
    - name: Gather IOS Facts 02
      ios_facts:
        gather_subset: all
      register: all_subset
    - name: Print Subset All 03
      debug:
        var: all_subset
